image: node:6.11.5

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - make configure-functions-staging
    - npm install -g firebase-tools
    - yarn
    - yarn lint
    - (cd functions; yarn)
    - firebase use --token $FIREBASE_DEPLOY_KEY_STAGING qpa-staging
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_STAGING