image: node:6.11.5

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - npm install -g firebase-tools
    - yarn
    - (cd functions; yarn)
    - firebase use --token $FIREBASE_DEPLOY_KEY_STAGING qpa-staging
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_STAGING