image: ubuntu:18.04

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - apt-get update
    - apt-get install -y node docker
    - (cd server; yarn build)
    - (cd client; yarn build)
    - docker build -t registry.gitlab.com/amiiit/gcf-auth:$CI_COMMIT_SHA .
