image: circleci/node:lts

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - tags
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn global add typescript
    - (cd server; yarn; yarn build)
    - docker build -t eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG .
    - docker push eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG
