image: ubuntu:18.04

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - apt-get update
    - apt-get install -y nodejs docker
    - (cd server; yarn build)
    - docker build -t eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG .
    - docker push eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG
