image: devillex/docker-firebase:latest

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - yarn
    - (cd server; yarn build)
    - (cd client; yarn build)
    - docker build -t registry.gitlab.com/amiiit/gcf-auth:$CI_COMMIT_SHA .
