image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - firebase use --token $FIREBASE_DEPLOY_KEY_STAGING production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_STAGING