stages:
  - build
  - release

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - yarn
    - yarn build

services:
  - docker:dind

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment:
    name: staging
  only:
    - tags
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn global add typescript
    - (cd server; yarn; yarn build)
    - (cd server; docker build -t eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG .)
    - docker push eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG
